Homepage ux update
dapplooker/graphlooker pull request #89
Opened 2022-08-19 06:21 UTC by harshrjjpt

2022-08-19 06:50 UTC, SumitMish23 commented on src/components/Footer/footer.scss
> +  color: $colorBlack;
Add Border shadow in the footer

2022-08-20 05:34 UTC, tech-nerd requested changes
<img width="1753" alt="image" src="https://user-images.githubusercontent.com/57493336/185730350-59867fd9-aca4-48c3-a83c-3c8a17057eba.png">
1. On hover the DOCS color is changed to a dark theme color, which is not the case in the new UX.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/57493336/185730392-4cae292e-1b7e-4fde-be93-76793c86b64f.png">
1. button colors 0f explore button and docs button are different

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/57493336/185730898-552df6c8-b430-49fe-96d5-a03a5cf8c779.png">
1. After input endpoint, input box background color changes

2022-08-20 07:03 UTC, deepakkashyap3013 commented
1. Footer upper shadow is not implemented :point_down: 

![Screenshot from 2022-08-20 12-12-07](https://user-images.githubusercontent.com/68886718/185732804-16c1c371-4692-45a5-af69-b93b180a0950.png)

2. When the view height is changed the footer postition changes

![Screenshot from 2022-08-20 12-15-38](https://user-images.githubusercontent.com/68886718/185732903-c8ef1023-5b3f-43b2-96f1-e0b28bc8085b.png)

4. 
- Remove the column Gap 
- Don't use margin 
- Reduce the width of the parent div for Subgraph links ( .subgraph-link-container{...} )

![Screenshot from 2022-08-20 12-24-17](https://user-images.githubusercontent.com/68886718/185733127-1ca8eb3c-42e1-4d7f-b536-eb51c61c15d6.png)

5. It should look soemthing like this :point_down: 

![Screenshot from 2022-08-20 12-27-01](https://user-images.githubusercontent.com/68886718/185733233-d924c3c6-66d5-4028-9ff1-9f3335f21f56.png)

2022-08-20 07:14 UTC, deepakkashyap3013 commented
**Don't use margin to manipulate the position of the elelemts**
- Instead Control the postition of the elements through the parent containers.
- If we continue to postion the elements using margin in future maintaining the code is very difficult. 
- Use margins whenever necessary

- Also the Text elements in the capsule are not in perfect center... please fix it

![Screenshot from 2022-08-20 12-36-15](https://user-images.githubusercontent.com/68886718/185733585-c0e53fa8-891f-4283-af5c-a7320521b6d4.png)
![Screenshot from 2022-08-20 12-36-25](https://user-images.githubusercontent.com/68886718/185733587-0f8eebe1-20e1-44f5-8bee-e7092c68cf43.png)
![Screenshot from 2022-08-20 12-36-28](https://user-images.githubusercontent.com/68886718/185733589-0904711e-c315-4736-bd5e-08459707a121.png)
![Screenshot from 2022-08-20 12-36-56](https://user-images.githubusercontent.com/68886718/185733592-2c6c989c-b2da-4c71-abeb-083ea3703acd.png)

2022-08-20 12:53 UTC, deepakkashyap3013 commented
![Screenshot from 2022-08-20 18-21-12](https://user-images.githubusercontent.com/68886718/185747037-f50b3aca-49b6-4d25-aca4-f01000b401f3.png)

Few Changes :
- Change the width to 888px
- Add the column gap to 50px

Rest Everything looks fine !

2022-08-21 08:29 UTC, tech-nerd requested changes

2022-08-21 08:29 UTC, tech-nerd commented on src/components/Footer/Footer.tsx
> +        <div className="left">
can we change class name to 'left-container', that will be the more logical name

2022-08-21 08:29 UTC, tech-nerd commented on src/components/Footer/Footer.tsx
> +        <div className="right">
can we change the class name to 'right-container', that will be a more logical name

2022-08-21 08:29 UTC, tech-nerd commented on src/components/Home/home.scss
> +      .error-message {
why empty classes

2022-08-21 08:29 UTC, tech-nerd commented on src/components/Home/home.scss
> +      .error-message {
why empty classes

2022-08-21 08:29 UTC, tech-nerd commented on src/components/Home/home.scss
> +          .search-button {
why empty classes

2022-08-21 08:29 UTC, tech-nerd commented on src/components/Home/home.scss
> +          li {
why empty classes

2022-08-21 08:29 UTC, tech-nerd commented on src/components/Home/home.scss
> +          .search-button {
why empty classes

2022-08-21 08:29 UTC, tech-nerd commented on src/components/Home/home.scss
> +                  .link-text {
why empty classes

2022-08-21 08:29 UTC, tech-nerd commented on src/components/Home/home.tsx
> +                        className="redirect-to-docs"
Code is not formatted

2022-08-21 08:29 UTC, tech-nerd commented on src/components/Navbar/navbar.tsx
>                    src="/images/GraphLooker_theme_color_text.png"
Please format the code

2022-08-21 08:29 UTC, tech-nerd commented on src/components/Navbar/navbar.tsx
>                    src="/images/GraphLooker_white_text.png"
Please format the code

2022-08-21 08:30 UTC, tech-nerd requested changes
<img width="1783" alt="image" src="https://user-images.githubusercontent.com/57493336/185782742-3f1f2fcf-009b-4b3b-ae68-75c754839ef5.png">
Footer is not sticking to bottom

2022-08-22 14:10 UTC, tech-nerd requested changes

2022-08-23 07:45 UTC, tech-nerd approved these changes

2022-08-23 07:46 UTC, merged