Datapage UX Update
dapplooker/graphlooker pull request #92
Opened 2022-08-24 08:32 UTC by SumitMish23

**---------> UI & UX Changes For DATA-BOARD <---------**

 **NavBar**
-> Changed the Background Colors & Box Shadows for the Docs,Export and Theme Buttons.
-> Updated the CSV and Theme Buttons in export-to-csv and graph-data components.
-> Updated the Size of Graphlooker Logo Icons for screen sizes below 800px.
-> Added Border-Shadow in the navbar as demonstrated in the Figma.

**AppBar (Drawer)**
-> Added App Heading class which consists of **Heading title** and **Drawer Collapse button** for closing the app bar.
-> Changed the text fonts & size of the List Item inside the ListItem Component.
-> Replaced the existing logo for displaying the entities.
-> Changed the Margins & Padding around each list item.

**Graph-Data**
-> Added **Copy** Functionality ,So the user can copy any given data in the table cell by clicking on it.
-> Added CSS For Copy Icon.
->Removed Tooltip from the table cell.

**Graph-Data-Table**
-> Replaced the existing **ternany operators** for selecting a classname with the **specified function** named as getClassNameByEntity.
-> Fixed the issue of rolling pagination container by adding the classes in CSS.
-> Changed the Button and Icons for **pagination container**.
-> Added CSS for Dynamically changing **data-table height** based on the filters selected.
->Added Customized **Scrollbars** for the graph data table.

**Additional Changes**
->Added Background and Border Shadows in the theme variable file.
->Added Text Name in the Constant File. 
->Added Fonts in the index file.

**-------> Images <-------**
Before the changes have implemented:
![image](https://user-images.githubusercontent.com/78703736/186368263-7f97fa53-3c5e-4c79-837d-38019273cd66.png)

After the Changes :
(i) **FULL PAGE**
![image](https://user-images.githubusercontent.com/78703736/186368959-4f8e00df-d116-4d9d-b6a4-6a5a7cf1ec79.png)
![image](https://user-images.githubusercontent.com/78703736/186369091-6559e435-9eb8-4503-8cf4-c4deb658ac07.png)

(ii)**Iphone SE**
![image](https://user-images.githubusercontent.com/78703736/186366791-08071ba7-417b-4d75-ac31-b9c9b500de37.png)

(iii)**Iphone XR**
![image](https://user-images.githubusercontent.com/78703736/186366845-e0eb4326-1623-4050-b10f-326217b1de82.png)

(iv)**Pixel 5**
![image](https://user-images.githubusercontent.com/78703736/186366909-7397b709-6d19-4354-a606-3931ef9277f1.png)

(v)**Ipad Mini**
![image](https://user-images.githubusercontent.com/78703736/186366973-80ae0e3f-393b-491c-846f-20e6633c32d5.png)

(vi)**Samsung Galaxy** 
![image](https://user-images.githubusercontent.com/78703736/186367050-cb8ced0f-07d0-4a0a-b160-80bc04a35dab.png)
![image](https://user-images.githubusercontent.com/78703736/186367177-94743d3e-4bd6-4a11-963a-3ac0bc95721e.png)

2022-08-24 10:53 UTC, harshrjjpt commented on src/components/GraphDataTable/graph-data-table.scss
> +
remove empty lines..

2022-08-24 11:09 UTC, harshrjjpt commented on src/utility/theme/dark-theme.scss
> +  --iconBackgroundColor: #44ABE7;   //2.0
remove comment

2022-08-24 11:09 UTC, harshrjjpt commented on src/components/GraphData/graph-data.tsx
>          <AppBar position="fixed" className="app-bar">
graphlooker logo width is not perfect below 600px.

2022-08-26 14:38 UTC, tech-nerd requested changes
<img width="52" alt="image" src="https://user-images.githubusercontent.com/57493336/186926007-a3657ae7-d879-42c9-9c9c-1319686015be.png">
- In mobile download, icon position is not correct or in center

<img width="700" alt="image" src="https://user-images.githubusercontent.com/57493336/186926148-03329d1b-4a5e-470b-9a82-0c265f614fd3.png">

- In mobile and web view pagination buttons are not correctly aligned as per UX designs

2022-08-26 14:38 UTC, tech-nerd commented on src/components/PrimaryMenu/primary-menu.scss
> +  background-color:#ECEAEA;
get it from varibale

2022-08-26 14:38 UTC, tech-nerd commented on src/components/PrimaryMenu/primary-menu.scss
> +    color: #FFFFFF;
get it from varibale

2022-08-30 09:23 UTC, tech-nerd requested changes

2022-08-30 09:23 UTC, tech-nerd commented on src/components/GraphData/graph-data.scss
> +@import '../../utility/theme/constant-color-variables.scss';
rename "constant-color-variables.scss" to "common.scss"

2022-08-30 09:23 UTC, tech-nerd commented on src/components/GraphDataTable/graph-data-table.scss
> +        color: #000000;
get it from varaible

2022-08-30 09:23 UTC, tech-nerd commented on src/components/GraphDataTable/graph-data-table.scss
> +      color: #000000;
get it from variable

2022-08-30 09:23 UTC, tech-nerd commented on src/components/Navbar/navbar.scss
> +          margin-left: -1px;
don't use negative

2022-08-30 09:23 UTC, tech-nerd commented on src/utility/theme/constant-color-variables.scss
> +$iconbackgroundColor:#fff;
its same as #ffffff

2022-08-30 11:46 UTC, tech-nerd approved these changes

2022-08-30 11:47 UTC, merged